import type { Metadata } from 'next';
import ProvidersAndNavbar from '@/components/providers';
import './globals.css';
import dbConnect from '@/lib/mongodb';
import Footer from '@/components/footer';
import { Box, Stack } from '@mui/material';

export const metadata: Metadata = {
  title: 'Account Shopping',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  return (
    <html lang='en'>
      <body>
        <ProvidersAndNavbar>
          <Stack spacing={2} flex={1} bgcolor={'background.default'} color={'text.primary'}>
            <Box flex={2}>{children}</Box>
            <Footer />
          </Stack>
        </ProvidersAndNavbar>
      </body>
    </html>
  );
}
